import '@components/layout';
import '@components/navigation';
import '@components/theme-switcher';
import '@components/custom-cursor';
import '@components/cursor-follow';
import '@components/gradient-divider';
import '@components/highlighted-text';
import '@components/section-reveal';
import './styles.css';
